// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module alveo_hls4ml_srn_ap_fixed_ap_fixed_32_16_5_3_0_config11_Pipeline_RndNormElementLoop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rnd_array_V_address0,
        rnd_array_V_ce0,
        rnd_array_V_q0,
        rnd_array_V_1_address0,
        rnd_array_V_1_ce0,
        rnd_array_V_1_q0,
        rnd_array_V_2_address0,
        rnd_array_V_2_ce0,
        rnd_array_V_2_q0,
        rnd_array_V_3_address0,
        rnd_array_V_3_ce0,
        rnd_array_V_3_q0,
        rnd_V_63_out,
        rnd_V_63_out_ap_vld,
        rnd_V_62_out,
        rnd_V_62_out_ap_vld,
        rnd_V_61_out,
        rnd_V_61_out_ap_vld,
        rnd_V_60_out,
        rnd_V_60_out_ap_vld,
        rnd_V_59_out,
        rnd_V_59_out_ap_vld,
        rnd_V_58_out,
        rnd_V_58_out_ap_vld,
        rnd_V_57_out,
        rnd_V_57_out_ap_vld,
        rnd_V_56_out,
        rnd_V_56_out_ap_vld,
        rnd_V_55_out,
        rnd_V_55_out_ap_vld,
        rnd_V_54_out,
        rnd_V_54_out_ap_vld,
        rnd_V_53_out,
        rnd_V_53_out_ap_vld,
        rnd_V_52_out,
        rnd_V_52_out_ap_vld,
        rnd_V_51_out,
        rnd_V_51_out_ap_vld,
        rnd_V_50_out,
        rnd_V_50_out_ap_vld,
        rnd_V_49_out,
        rnd_V_49_out_ap_vld,
        rnd_V_48_out,
        rnd_V_48_out_ap_vld,
        rnd_V_47_out,
        rnd_V_47_out_ap_vld,
        rnd_V_46_out,
        rnd_V_46_out_ap_vld,
        rnd_V_45_out,
        rnd_V_45_out_ap_vld,
        rnd_V_44_out,
        rnd_V_44_out_ap_vld,
        rnd_V_43_out,
        rnd_V_43_out_ap_vld,
        rnd_V_42_out,
        rnd_V_42_out_ap_vld,
        rnd_V_41_out,
        rnd_V_41_out_ap_vld,
        rnd_V_40_out,
        rnd_V_40_out_ap_vld,
        rnd_V_39_out,
        rnd_V_39_out_ap_vld,
        rnd_V_38_out,
        rnd_V_38_out_ap_vld,
        rnd_V_37_out,
        rnd_V_37_out_ap_vld,
        rnd_V_36_out,
        rnd_V_36_out_ap_vld,
        rnd_V_35_out,
        rnd_V_35_out_ap_vld,
        rnd_V_34_out,
        rnd_V_34_out_ap_vld,
        rnd_V_33_out,
        rnd_V_33_out_ap_vld,
        rnd_V_32_out,
        rnd_V_32_out_ap_vld,
        rnd_V_31_out,
        rnd_V_31_out_ap_vld,
        rnd_V_30_out,
        rnd_V_30_out_ap_vld,
        rnd_V_29_out,
        rnd_V_29_out_ap_vld,
        rnd_V_28_out,
        rnd_V_28_out_ap_vld,
        rnd_V_27_out,
        rnd_V_27_out_ap_vld,
        rnd_V_26_out,
        rnd_V_26_out_ap_vld,
        rnd_V_25_out,
        rnd_V_25_out_ap_vld,
        rnd_V_24_out,
        rnd_V_24_out_ap_vld,
        rnd_V_23_out,
        rnd_V_23_out_ap_vld,
        rnd_V_22_out,
        rnd_V_22_out_ap_vld,
        rnd_V_21_out,
        rnd_V_21_out_ap_vld,
        rnd_V_20_out,
        rnd_V_20_out_ap_vld,
        rnd_V_19_out,
        rnd_V_19_out_ap_vld,
        rnd_V_18_out,
        rnd_V_18_out_ap_vld,
        rnd_V_17_out,
        rnd_V_17_out_ap_vld,
        rnd_V_16_out,
        rnd_V_16_out_ap_vld,
        rnd_V_15_out,
        rnd_V_15_out_ap_vld,
        rnd_V_14_out,
        rnd_V_14_out_ap_vld,
        rnd_V_13_out,
        rnd_V_13_out_ap_vld,
        rnd_V_12_out,
        rnd_V_12_out_ap_vld,
        rnd_V_11_out,
        rnd_V_11_out_ap_vld,
        rnd_V_10_out,
        rnd_V_10_out_ap_vld,
        rnd_V_9_out,
        rnd_V_9_out_ap_vld,
        rnd_V_8_out,
        rnd_V_8_out_ap_vld,
        rnd_V_7_out,
        rnd_V_7_out_ap_vld,
        rnd_V_6_out,
        rnd_V_6_out_ap_vld,
        rnd_V_5_out,
        rnd_V_5_out_ap_vld,
        rnd_V_4_out,
        rnd_V_4_out_ap_vld,
        rnd_V_3_out,
        rnd_V_3_out_ap_vld,
        rnd_V_2_out,
        rnd_V_2_out_ap_vld,
        rnd_V_1_out,
        rnd_V_1_out_ap_vld,
        rnd_V_out,
        rnd_V_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] rnd_array_V_address0;
output   rnd_array_V_ce0;
input  [31:0] rnd_array_V_q0;
output  [5:0] rnd_array_V_1_address0;
output   rnd_array_V_1_ce0;
input  [31:0] rnd_array_V_1_q0;
output  [5:0] rnd_array_V_2_address0;
output   rnd_array_V_2_ce0;
input  [31:0] rnd_array_V_2_q0;
output  [5:0] rnd_array_V_3_address0;
output   rnd_array_V_3_ce0;
input  [31:0] rnd_array_V_3_q0;
output  [31:0] rnd_V_63_out;
output   rnd_V_63_out_ap_vld;
output  [31:0] rnd_V_62_out;
output   rnd_V_62_out_ap_vld;
output  [31:0] rnd_V_61_out;
output   rnd_V_61_out_ap_vld;
output  [31:0] rnd_V_60_out;
output   rnd_V_60_out_ap_vld;
output  [31:0] rnd_V_59_out;
output   rnd_V_59_out_ap_vld;
output  [31:0] rnd_V_58_out;
output   rnd_V_58_out_ap_vld;
output  [31:0] rnd_V_57_out;
output   rnd_V_57_out_ap_vld;
output  [31:0] rnd_V_56_out;
output   rnd_V_56_out_ap_vld;
output  [31:0] rnd_V_55_out;
output   rnd_V_55_out_ap_vld;
output  [31:0] rnd_V_54_out;
output   rnd_V_54_out_ap_vld;
output  [31:0] rnd_V_53_out;
output   rnd_V_53_out_ap_vld;
output  [31:0] rnd_V_52_out;
output   rnd_V_52_out_ap_vld;
output  [31:0] rnd_V_51_out;
output   rnd_V_51_out_ap_vld;
output  [31:0] rnd_V_50_out;
output   rnd_V_50_out_ap_vld;
output  [31:0] rnd_V_49_out;
output   rnd_V_49_out_ap_vld;
output  [31:0] rnd_V_48_out;
output   rnd_V_48_out_ap_vld;
output  [31:0] rnd_V_47_out;
output   rnd_V_47_out_ap_vld;
output  [31:0] rnd_V_46_out;
output   rnd_V_46_out_ap_vld;
output  [31:0] rnd_V_45_out;
output   rnd_V_45_out_ap_vld;
output  [31:0] rnd_V_44_out;
output   rnd_V_44_out_ap_vld;
output  [31:0] rnd_V_43_out;
output   rnd_V_43_out_ap_vld;
output  [31:0] rnd_V_42_out;
output   rnd_V_42_out_ap_vld;
output  [31:0] rnd_V_41_out;
output   rnd_V_41_out_ap_vld;
output  [31:0] rnd_V_40_out;
output   rnd_V_40_out_ap_vld;
output  [31:0] rnd_V_39_out;
output   rnd_V_39_out_ap_vld;
output  [31:0] rnd_V_38_out;
output   rnd_V_38_out_ap_vld;
output  [31:0] rnd_V_37_out;
output   rnd_V_37_out_ap_vld;
output  [31:0] rnd_V_36_out;
output   rnd_V_36_out_ap_vld;
output  [31:0] rnd_V_35_out;
output   rnd_V_35_out_ap_vld;
output  [31:0] rnd_V_34_out;
output   rnd_V_34_out_ap_vld;
output  [31:0] rnd_V_33_out;
output   rnd_V_33_out_ap_vld;
output  [31:0] rnd_V_32_out;
output   rnd_V_32_out_ap_vld;
output  [31:0] rnd_V_31_out;
output   rnd_V_31_out_ap_vld;
output  [31:0] rnd_V_30_out;
output   rnd_V_30_out_ap_vld;
output  [31:0] rnd_V_29_out;
output   rnd_V_29_out_ap_vld;
output  [31:0] rnd_V_28_out;
output   rnd_V_28_out_ap_vld;
output  [31:0] rnd_V_27_out;
output   rnd_V_27_out_ap_vld;
output  [31:0] rnd_V_26_out;
output   rnd_V_26_out_ap_vld;
output  [31:0] rnd_V_25_out;
output   rnd_V_25_out_ap_vld;
output  [31:0] rnd_V_24_out;
output   rnd_V_24_out_ap_vld;
output  [31:0] rnd_V_23_out;
output   rnd_V_23_out_ap_vld;
output  [31:0] rnd_V_22_out;
output   rnd_V_22_out_ap_vld;
output  [31:0] rnd_V_21_out;
output   rnd_V_21_out_ap_vld;
output  [31:0] rnd_V_20_out;
output   rnd_V_20_out_ap_vld;
output  [31:0] rnd_V_19_out;
output   rnd_V_19_out_ap_vld;
output  [31:0] rnd_V_18_out;
output   rnd_V_18_out_ap_vld;
output  [31:0] rnd_V_17_out;
output   rnd_V_17_out_ap_vld;
output  [31:0] rnd_V_16_out;
output   rnd_V_16_out_ap_vld;
output  [31:0] rnd_V_15_out;
output   rnd_V_15_out_ap_vld;
output  [31:0] rnd_V_14_out;
output   rnd_V_14_out_ap_vld;
output  [31:0] rnd_V_13_out;
output   rnd_V_13_out_ap_vld;
output  [31:0] rnd_V_12_out;
output   rnd_V_12_out_ap_vld;
output  [31:0] rnd_V_11_out;
output   rnd_V_11_out_ap_vld;
output  [31:0] rnd_V_10_out;
output   rnd_V_10_out_ap_vld;
output  [31:0] rnd_V_9_out;
output   rnd_V_9_out_ap_vld;
output  [31:0] rnd_V_8_out;
output   rnd_V_8_out_ap_vld;
output  [31:0] rnd_V_7_out;
output   rnd_V_7_out_ap_vld;
output  [31:0] rnd_V_6_out;
output   rnd_V_6_out_ap_vld;
output  [31:0] rnd_V_5_out;
output   rnd_V_5_out_ap_vld;
output  [31:0] rnd_V_4_out;
output   rnd_V_4_out_ap_vld;
output  [31:0] rnd_V_3_out;
output   rnd_V_3_out_ap_vld;
output  [31:0] rnd_V_2_out;
output   rnd_V_2_out_ap_vld;
output  [31:0] rnd_V_1_out;
output   rnd_V_1_out_ap_vld;
output  [31:0] rnd_V_out;
output   rnd_V_out_ap_vld;

reg ap_idle;
reg rnd_array_V_ce0;
reg rnd_array_V_1_ce0;
reg rnd_array_V_2_ce0;
reg rnd_array_V_3_ce0;
reg rnd_V_63_out_ap_vld;
reg rnd_V_62_out_ap_vld;
reg rnd_V_61_out_ap_vld;
reg rnd_V_60_out_ap_vld;
reg rnd_V_59_out_ap_vld;
reg rnd_V_58_out_ap_vld;
reg rnd_V_57_out_ap_vld;
reg rnd_V_56_out_ap_vld;
reg rnd_V_55_out_ap_vld;
reg rnd_V_54_out_ap_vld;
reg rnd_V_53_out_ap_vld;
reg rnd_V_52_out_ap_vld;
reg rnd_V_51_out_ap_vld;
reg rnd_V_50_out_ap_vld;
reg rnd_V_49_out_ap_vld;
reg rnd_V_48_out_ap_vld;
reg rnd_V_47_out_ap_vld;
reg rnd_V_46_out_ap_vld;
reg rnd_V_45_out_ap_vld;
reg rnd_V_44_out_ap_vld;
reg rnd_V_43_out_ap_vld;
reg rnd_V_42_out_ap_vld;
reg rnd_V_41_out_ap_vld;
reg rnd_V_40_out_ap_vld;
reg rnd_V_39_out_ap_vld;
reg rnd_V_38_out_ap_vld;
reg rnd_V_37_out_ap_vld;
reg rnd_V_36_out_ap_vld;
reg rnd_V_35_out_ap_vld;
reg rnd_V_34_out_ap_vld;
reg rnd_V_33_out_ap_vld;
reg rnd_V_32_out_ap_vld;
reg rnd_V_31_out_ap_vld;
reg rnd_V_30_out_ap_vld;
reg rnd_V_29_out_ap_vld;
reg rnd_V_28_out_ap_vld;
reg rnd_V_27_out_ap_vld;
reg rnd_V_26_out_ap_vld;
reg rnd_V_25_out_ap_vld;
reg rnd_V_24_out_ap_vld;
reg rnd_V_23_out_ap_vld;
reg rnd_V_22_out_ap_vld;
reg rnd_V_21_out_ap_vld;
reg rnd_V_20_out_ap_vld;
reg rnd_V_19_out_ap_vld;
reg rnd_V_18_out_ap_vld;
reg rnd_V_17_out_ap_vld;
reg rnd_V_16_out_ap_vld;
reg rnd_V_15_out_ap_vld;
reg rnd_V_14_out_ap_vld;
reg rnd_V_13_out_ap_vld;
reg rnd_V_12_out_ap_vld;
reg rnd_V_11_out_ap_vld;
reg rnd_V_10_out_ap_vld;
reg rnd_V_9_out_ap_vld;
reg rnd_V_8_out_ap_vld;
reg rnd_V_7_out_ap_vld;
reg rnd_V_6_out_ap_vld;
reg rnd_V_5_out_ap_vld;
reg rnd_V_4_out_ap_vld;
reg rnd_V_3_out_ap_vld;
reg rnd_V_2_out_ap_vld;
reg rnd_V_1_out_ap_vld;
reg rnd_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln235_fu_1066_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln235_reg_2127;
reg   [0:0] icmp_ln235_reg_2127_pp0_iter1_reg;
wire   [5:0] trunc_ln240_fu_1086_p1;
reg   [5:0] trunc_ln240_reg_2151;
reg   [5:0] trunc_ln240_reg_2151_pp0_iter1_reg;
reg   [5:0] trunc_ln240_reg_2151_pp0_iter2_reg;
wire   [33:0] r_V_fu_1131_p2;
reg  signed [33:0] r_V_reg_2155;
wire   [63:0] i_1_cast_fu_1078_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_298;
wire   [6:0] add_ln235_fu_1072_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [31:0] rnd_V_fu_302;
wire  signed [31:0] sext_ln818_fu_1156_p1;
reg   [31:0] rnd_V_1_fu_306;
reg   [31:0] rnd_V_2_fu_310;
reg   [31:0] rnd_V_3_fu_314;
reg   [31:0] rnd_V_4_fu_318;
reg   [31:0] rnd_V_5_fu_322;
reg   [31:0] rnd_V_6_fu_326;
reg   [31:0] rnd_V_7_fu_330;
reg   [31:0] rnd_V_8_fu_334;
reg   [31:0] rnd_V_9_fu_338;
reg   [31:0] rnd_V_10_fu_342;
reg   [31:0] rnd_V_11_fu_346;
reg   [31:0] rnd_V_12_fu_350;
reg   [31:0] rnd_V_13_fu_354;
reg   [31:0] rnd_V_14_fu_358;
reg   [31:0] rnd_V_15_fu_362;
reg   [31:0] rnd_V_16_fu_366;
reg   [31:0] rnd_V_17_fu_370;
reg   [31:0] rnd_V_18_fu_374;
reg   [31:0] rnd_V_19_fu_378;
reg   [31:0] rnd_V_20_fu_382;
reg   [31:0] rnd_V_21_fu_386;
reg   [31:0] rnd_V_22_fu_390;
reg   [31:0] rnd_V_23_fu_394;
reg   [31:0] rnd_V_24_fu_398;
reg   [31:0] rnd_V_25_fu_402;
reg   [31:0] rnd_V_26_fu_406;
reg   [31:0] rnd_V_27_fu_410;
reg   [31:0] rnd_V_28_fu_414;
reg   [31:0] rnd_V_29_fu_418;
reg   [31:0] rnd_V_30_fu_422;
reg   [31:0] rnd_V_31_fu_426;
reg   [31:0] rnd_V_32_fu_430;
reg   [31:0] rnd_V_33_fu_434;
reg   [31:0] rnd_V_34_fu_438;
reg   [31:0] rnd_V_35_fu_442;
reg   [31:0] rnd_V_36_fu_446;
reg   [31:0] rnd_V_37_fu_450;
reg   [31:0] rnd_V_38_fu_454;
reg   [31:0] rnd_V_39_fu_458;
reg   [31:0] rnd_V_40_fu_462;
reg   [31:0] rnd_V_41_fu_466;
reg   [31:0] rnd_V_42_fu_470;
reg   [31:0] rnd_V_43_fu_474;
reg   [31:0] rnd_V_44_fu_478;
reg   [31:0] rnd_V_45_fu_482;
reg   [31:0] rnd_V_46_fu_486;
reg   [31:0] rnd_V_47_fu_490;
reg   [31:0] rnd_V_48_fu_494;
reg   [31:0] rnd_V_49_fu_498;
reg   [31:0] rnd_V_50_fu_502;
reg   [31:0] rnd_V_51_fu_506;
reg   [31:0] rnd_V_52_fu_510;
reg   [31:0] rnd_V_53_fu_514;
reg   [31:0] rnd_V_54_fu_518;
reg   [31:0] rnd_V_55_fu_522;
reg   [31:0] rnd_V_56_fu_526;
reg   [31:0] rnd_V_57_fu_530;
reg   [31:0] rnd_V_58_fu_534;
reg   [31:0] rnd_V_59_fu_538;
reg   [31:0] rnd_V_60_fu_542;
reg   [31:0] rnd_V_61_fu_546;
reg   [31:0] rnd_V_62_fu_550;
reg   [31:0] rnd_V_63_fu_554;
wire    ap_block_pp0_stage0_01001;
wire  signed [32:0] sext_ln840_1_fu_1099_p1;
wire  signed [32:0] sext_ln840_fu_1095_p1;
wire   [32:0] add_ln840_fu_1103_p2;
wire  signed [32:0] sext_ln840_3_fu_1113_p1;
wire  signed [32:0] sext_ln840_4_fu_1117_p1;
wire   [32:0] add_ln840_1_fu_1121_p2;
wire  signed [33:0] sext_ln840_5_fu_1127_p1;
wire  signed [33:0] sext_ln840_2_fu_1109_p1;
wire   [33:0] grp_fu_1140_p1;
wire   [66:0] grp_fu_1140_p2;
wire   [18:0] rnd_V_64_fu_1146_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

alveo_hls4ml_mul_34s_34ns_67_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 67 ))
mul_34s_34ns_67_2_1_U4258(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_reg_2155),
    .din1(grp_fu_1140_p1),
    .ce(1'b1),
    .dout(grp_fu_1140_p2)
);

alveo_hls4ml_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln235_fu_1066_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_298 <= add_ln235_fu_1072_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_298 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln235_reg_2127 <= icmp_ln235_fu_1066_p2;
        icmp_ln235_reg_2127_pp0_iter1_reg <= icmp_ln235_reg_2127;
        r_V_reg_2155 <= r_V_fu_1131_p2;
        trunc_ln240_reg_2151_pp0_iter1_reg <= trunc_ln240_reg_2151;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_10_fu_342 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_11_fu_346 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_12_fu_350 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_13_fu_354 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_14_fu_358 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_15_fu_362 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd16) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_16_fu_366 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd17) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_17_fu_370 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd18) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_18_fu_374 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd19) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_19_fu_378 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_1_fu_306 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd20) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_20_fu_382 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd21) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_21_fu_386 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd22) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_22_fu_390 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd23) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_23_fu_394 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_24_fu_398 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd25) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_25_fu_402 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd26) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_26_fu_406 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd27) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_27_fu_410 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd28) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_28_fu_414 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd29) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_29_fu_418 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_2_fu_310 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd30) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_30_fu_422 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd31) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_31_fu_426 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd32) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_32_fu_430 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd33) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_33_fu_434 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd34) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_34_fu_438 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd35) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_35_fu_442 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd36) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_36_fu_446 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd37) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_37_fu_450 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd38) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_38_fu_454 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd39) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_39_fu_458 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_3_fu_314 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd40) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_40_fu_462 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd41) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_41_fu_466 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd42) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_42_fu_470 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd43) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_43_fu_474 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd44) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_44_fu_478 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd45) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_45_fu_482 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd46) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_46_fu_486 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd47) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_47_fu_490 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd48) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_48_fu_494 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd49) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_49_fu_498 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_4_fu_318 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd50) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_50_fu_502 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd51) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_51_fu_506 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd52) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_52_fu_510 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd53) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_53_fu_514 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd54) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_54_fu_518 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd55) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_55_fu_522 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd56) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_56_fu_526 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd57) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_57_fu_530 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd58) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_58_fu_534 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd59) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_59_fu_538 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_5_fu_322 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd60) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_60_fu_542 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd61) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_61_fu_546 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd62) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_62_fu_550 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd63) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_63_fu_554 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_6_fu_326 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_7_fu_330 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_8_fu_334 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_9_fu_338 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln240_reg_2151_pp0_iter2_reg == 6'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        rnd_V_fu_302 <= sext_ln818_fu_1156_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln235_fu_1066_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln240_reg_2151 <= trunc_ln240_fu_1086_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        trunc_ln240_reg_2151_pp0_iter2_reg <= trunc_ln240_reg_2151_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln235_fu_1066_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_298;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_10_out_ap_vld = 1'b1;
    end else begin
        rnd_V_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_11_out_ap_vld = 1'b1;
    end else begin
        rnd_V_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_12_out_ap_vld = 1'b1;
    end else begin
        rnd_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_13_out_ap_vld = 1'b1;
    end else begin
        rnd_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_14_out_ap_vld = 1'b1;
    end else begin
        rnd_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_15_out_ap_vld = 1'b1;
    end else begin
        rnd_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_16_out_ap_vld = 1'b1;
    end else begin
        rnd_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_17_out_ap_vld = 1'b1;
    end else begin
        rnd_V_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_18_out_ap_vld = 1'b1;
    end else begin
        rnd_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_19_out_ap_vld = 1'b1;
    end else begin
        rnd_V_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_1_out_ap_vld = 1'b1;
    end else begin
        rnd_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_20_out_ap_vld = 1'b1;
    end else begin
        rnd_V_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_21_out_ap_vld = 1'b1;
    end else begin
        rnd_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_22_out_ap_vld = 1'b1;
    end else begin
        rnd_V_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_23_out_ap_vld = 1'b1;
    end else begin
        rnd_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_24_out_ap_vld = 1'b1;
    end else begin
        rnd_V_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_25_out_ap_vld = 1'b1;
    end else begin
        rnd_V_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_26_out_ap_vld = 1'b1;
    end else begin
        rnd_V_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_27_out_ap_vld = 1'b1;
    end else begin
        rnd_V_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_28_out_ap_vld = 1'b1;
    end else begin
        rnd_V_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_29_out_ap_vld = 1'b1;
    end else begin
        rnd_V_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_2_out_ap_vld = 1'b1;
    end else begin
        rnd_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_30_out_ap_vld = 1'b1;
    end else begin
        rnd_V_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_31_out_ap_vld = 1'b1;
    end else begin
        rnd_V_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_32_out_ap_vld = 1'b1;
    end else begin
        rnd_V_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_33_out_ap_vld = 1'b1;
    end else begin
        rnd_V_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_34_out_ap_vld = 1'b1;
    end else begin
        rnd_V_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_35_out_ap_vld = 1'b1;
    end else begin
        rnd_V_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_36_out_ap_vld = 1'b1;
    end else begin
        rnd_V_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_37_out_ap_vld = 1'b1;
    end else begin
        rnd_V_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_38_out_ap_vld = 1'b1;
    end else begin
        rnd_V_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_39_out_ap_vld = 1'b1;
    end else begin
        rnd_V_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_3_out_ap_vld = 1'b1;
    end else begin
        rnd_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_40_out_ap_vld = 1'b1;
    end else begin
        rnd_V_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_41_out_ap_vld = 1'b1;
    end else begin
        rnd_V_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_42_out_ap_vld = 1'b1;
    end else begin
        rnd_V_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_43_out_ap_vld = 1'b1;
    end else begin
        rnd_V_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_44_out_ap_vld = 1'b1;
    end else begin
        rnd_V_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_45_out_ap_vld = 1'b1;
    end else begin
        rnd_V_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_46_out_ap_vld = 1'b1;
    end else begin
        rnd_V_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_47_out_ap_vld = 1'b1;
    end else begin
        rnd_V_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_48_out_ap_vld = 1'b1;
    end else begin
        rnd_V_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_49_out_ap_vld = 1'b1;
    end else begin
        rnd_V_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_4_out_ap_vld = 1'b1;
    end else begin
        rnd_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_50_out_ap_vld = 1'b1;
    end else begin
        rnd_V_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_51_out_ap_vld = 1'b1;
    end else begin
        rnd_V_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_52_out_ap_vld = 1'b1;
    end else begin
        rnd_V_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_53_out_ap_vld = 1'b1;
    end else begin
        rnd_V_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_54_out_ap_vld = 1'b1;
    end else begin
        rnd_V_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_55_out_ap_vld = 1'b1;
    end else begin
        rnd_V_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_56_out_ap_vld = 1'b1;
    end else begin
        rnd_V_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_57_out_ap_vld = 1'b1;
    end else begin
        rnd_V_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_58_out_ap_vld = 1'b1;
    end else begin
        rnd_V_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_59_out_ap_vld = 1'b1;
    end else begin
        rnd_V_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_5_out_ap_vld = 1'b1;
    end else begin
        rnd_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_60_out_ap_vld = 1'b1;
    end else begin
        rnd_V_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_61_out_ap_vld = 1'b1;
    end else begin
        rnd_V_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_62_out_ap_vld = 1'b1;
    end else begin
        rnd_V_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_63_out_ap_vld = 1'b1;
    end else begin
        rnd_V_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_6_out_ap_vld = 1'b1;
    end else begin
        rnd_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_7_out_ap_vld = 1'b1;
    end else begin
        rnd_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_8_out_ap_vld = 1'b1;
    end else begin
        rnd_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_9_out_ap_vld = 1'b1;
    end else begin
        rnd_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln235_reg_2127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rnd_V_out_ap_vld = 1'b1;
    end else begin
        rnd_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rnd_array_V_1_ce0 = 1'b1;
    end else begin
        rnd_array_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rnd_array_V_2_ce0 = 1'b1;
    end else begin
        rnd_array_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rnd_array_V_3_ce0 = 1'b1;
    end else begin
        rnd_array_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rnd_array_V_ce0 = 1'b1;
    end else begin
        rnd_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln235_fu_1072_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign add_ln840_1_fu_1121_p2 = ($signed(sext_ln840_3_fu_1113_p1) + $signed(sext_ln840_4_fu_1117_p1));

assign add_ln840_fu_1103_p2 = ($signed(sext_ln840_1_fu_1099_p1) + $signed(sext_ln840_fu_1095_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_1140_p1 = 67'd7437903818;

assign i_1_cast_fu_1078_p1 = ap_sig_allocacmp_i_1;

assign icmp_ln235_fu_1066_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign r_V_fu_1131_p2 = ($signed(sext_ln840_5_fu_1127_p1) + $signed(sext_ln840_2_fu_1109_p1));

assign rnd_V_10_out = rnd_V_10_fu_342;

assign rnd_V_11_out = rnd_V_11_fu_346;

assign rnd_V_12_out = rnd_V_12_fu_350;

assign rnd_V_13_out = rnd_V_13_fu_354;

assign rnd_V_14_out = rnd_V_14_fu_358;

assign rnd_V_15_out = rnd_V_15_fu_362;

assign rnd_V_16_out = rnd_V_16_fu_366;

assign rnd_V_17_out = rnd_V_17_fu_370;

assign rnd_V_18_out = rnd_V_18_fu_374;

assign rnd_V_19_out = rnd_V_19_fu_378;

assign rnd_V_1_out = rnd_V_1_fu_306;

assign rnd_V_20_out = rnd_V_20_fu_382;

assign rnd_V_21_out = rnd_V_21_fu_386;

assign rnd_V_22_out = rnd_V_22_fu_390;

assign rnd_V_23_out = rnd_V_23_fu_394;

assign rnd_V_24_out = rnd_V_24_fu_398;

assign rnd_V_25_out = rnd_V_25_fu_402;

assign rnd_V_26_out = rnd_V_26_fu_406;

assign rnd_V_27_out = rnd_V_27_fu_410;

assign rnd_V_28_out = rnd_V_28_fu_414;

assign rnd_V_29_out = rnd_V_29_fu_418;

assign rnd_V_2_out = rnd_V_2_fu_310;

assign rnd_V_30_out = rnd_V_30_fu_422;

assign rnd_V_31_out = rnd_V_31_fu_426;

assign rnd_V_32_out = rnd_V_32_fu_430;

assign rnd_V_33_out = rnd_V_33_fu_434;

assign rnd_V_34_out = rnd_V_34_fu_438;

assign rnd_V_35_out = rnd_V_35_fu_442;

assign rnd_V_36_out = rnd_V_36_fu_446;

assign rnd_V_37_out = rnd_V_37_fu_450;

assign rnd_V_38_out = rnd_V_38_fu_454;

assign rnd_V_39_out = rnd_V_39_fu_458;

assign rnd_V_3_out = rnd_V_3_fu_314;

assign rnd_V_40_out = rnd_V_40_fu_462;

assign rnd_V_41_out = rnd_V_41_fu_466;

assign rnd_V_42_out = rnd_V_42_fu_470;

assign rnd_V_43_out = rnd_V_43_fu_474;

assign rnd_V_44_out = rnd_V_44_fu_478;

assign rnd_V_45_out = rnd_V_45_fu_482;

assign rnd_V_46_out = rnd_V_46_fu_486;

assign rnd_V_47_out = rnd_V_47_fu_490;

assign rnd_V_48_out = rnd_V_48_fu_494;

assign rnd_V_49_out = rnd_V_49_fu_498;

assign rnd_V_4_out = rnd_V_4_fu_318;

assign rnd_V_50_out = rnd_V_50_fu_502;

assign rnd_V_51_out = rnd_V_51_fu_506;

assign rnd_V_52_out = rnd_V_52_fu_510;

assign rnd_V_53_out = rnd_V_53_fu_514;

assign rnd_V_54_out = rnd_V_54_fu_518;

assign rnd_V_55_out = rnd_V_55_fu_522;

assign rnd_V_56_out = rnd_V_56_fu_526;

assign rnd_V_57_out = rnd_V_57_fu_530;

assign rnd_V_58_out = rnd_V_58_fu_534;

assign rnd_V_59_out = rnd_V_59_fu_538;

assign rnd_V_5_out = rnd_V_5_fu_322;

assign rnd_V_60_out = rnd_V_60_fu_542;

assign rnd_V_61_out = rnd_V_61_fu_546;

assign rnd_V_62_out = rnd_V_62_fu_550;

assign rnd_V_63_out = rnd_V_63_fu_554;

assign rnd_V_64_fu_1146_p4 = {{grp_fu_1140_p2[66:48]}};

assign rnd_V_6_out = rnd_V_6_fu_326;

assign rnd_V_7_out = rnd_V_7_fu_330;

assign rnd_V_8_out = rnd_V_8_fu_334;

assign rnd_V_9_out = rnd_V_9_fu_338;

assign rnd_V_out = rnd_V_fu_302;

assign rnd_array_V_1_address0 = i_1_cast_fu_1078_p1;

assign rnd_array_V_2_address0 = i_1_cast_fu_1078_p1;

assign rnd_array_V_3_address0 = i_1_cast_fu_1078_p1;

assign rnd_array_V_address0 = i_1_cast_fu_1078_p1;

assign sext_ln818_fu_1156_p1 = $signed(rnd_V_64_fu_1146_p4);

assign sext_ln840_1_fu_1099_p1 = $signed(rnd_array_V_1_q0);

assign sext_ln840_2_fu_1109_p1 = $signed(add_ln840_fu_1103_p2);

assign sext_ln840_3_fu_1113_p1 = $signed(rnd_array_V_2_q0);

assign sext_ln840_4_fu_1117_p1 = $signed(rnd_array_V_3_q0);

assign sext_ln840_5_fu_1127_p1 = $signed(add_ln840_1_fu_1121_p2);

assign sext_ln840_fu_1095_p1 = $signed(rnd_array_V_q0);

assign trunc_ln240_fu_1086_p1 = ap_sig_allocacmp_i_1[5:0];

endmodule //alveo_hls4ml_srn_ap_fixed_ap_fixed_32_16_5_3_0_config11_Pipeline_RndNormElementLoop
